# Generated by Django 4.1.13 on 2024-03-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_users_chat_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['date_time']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='text',
            new_name='message',
        ),
    ]
