# Generated by Django 4.1.13 on 2024-03-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
    ]
