# Generated by Django 4.1.13 on 2024-03-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat',
        ),
    ]
