# Generated by Django 4.1.13 on 2024-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(upload_to='profile/image', verbose_name='Фото профиля'),
        ),
    ]
