# Generated by Django 4.1.13 on 2024-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0002_alter_customuser_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to='profile/image', verbose_name='Фото профиля'),
        ),
    ]
