# Generated by Django 4.1 on 2024-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0005_customuser_instagram_customuser_music_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='vk',
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Фэйсбук'),
        ),
    ]
