# Generated by Django 4.1 on 2024-07-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0006_remove_customuser_vk_customuser_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='music',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='videos',
        ),
    ]
