# Generated by Django 4.1 on 2024-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0007_remove_customuser_music_remove_customuser_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=250, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=250, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, max_length=150, verbose_name='Фэйсбук'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, max_length=150, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(blank=True, max_length=250, verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.TextField(blank=True, max_length=400, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.URLField(blank=True, max_length=150, verbose_name='Телеграм'),
        ),
    ]
